fix: abort if report can't be generated
Signed-off-by: Thomas Böhler <t.boehler@kunbus.com>

diff --git a/revpi-sos b/revpi-sos
--- a/revpi-sos
+++ b/revpi-sos
@@ -53,7 +53,13 @@ if [ "$FORCE" != "1" ]; then
 fi
 
 echo "generating SOS report..."
-SOSFILE=$(sudo sos report -o revpi,revpi-eep,revpi-codesys --batch | grep "/sosreport-.*\.tar" | sed -e 's/^[ \t]*//')
+SOSFILE="$(sudo sos report -o revpi,revpi-eep,revpi-codesys --batch)"
+if [ "$?" -ne 0 ]; then
+	echo "An error occurred while generating the SOS report." >&2
+	exit 1
+fi
+SOSFILE="$(echo "$SOSFILE" | grep "/sosreport-.*\.tar" | sed -e 's/^[ \t]*//')"
+
 echo
 echo "Your SOS report has been generated and saved to:"
 echo "$SOSFILE"
